Option to skip sync indexes
Non-fungible-Technologies/keystone-5 pull request #1
Opened 2022-01-18 23:52 UTC by pixxiec

Our experience is that the mongoose adapter has a method `syncIndexes` which is dropping all indices except the _id index every time the keystone application deploys. To mitigate this, I have implemented an env flag lookup called MONGOOSE_SYNC_INDEXES. In the mongoose adapter in keystone, where syncIndexes was called, there is now a check (default false) for this env variable. Going forward the only way to get the indices to rebuild on a deploy is to have MONGOOSE_SYNC_INDEXES = "true" as an env variable.

2022-01-19 00:24 UTC, jmagder commented
Awesome.  I'll try this out locally and verify after I finish with some support issues.

2022-01-19 17:32 UTC, jmagder commented
Are we sure we are using keystone-5?  The npm page is `@keystonejs/keystone` which I think is not keystone-5, but just keystone

2022-01-19 17:38 UTC, jterzis approved these changes

2022-01-19 18:04 UTC, jmagder requested changes
Wrong version of keystone was forked, we need https://github.com/keystonejs/keystone

2022-01-19 18:19 UTC, jmagder reviewed
I was wrong, you picked the right package.   https://www.npmjs.com/package/@keystonejs/keystone links to https://github.com/keystonejs/keystone-5/tree/main/packages/keystone  Will test it out!

2022-01-19 18:20 UTC, jmagder commented on packages/adapter-mongoose/lib/adapter-mongoose.js
> +const mongooseSyncIndexes = process.env.MONGOOSE_SYNC_INDEXES?.toLowerCase() === 'true' ? true : false;
This can just be `const mongooseSyncIndexes = process.env.MONGOOSE_SYNC_INDEXES?.toLowerCase() === 'true'`;

2022-01-20 03:33 UTC, jmagder approved these changes

2022-01-20 03:33 UTC, merged